### PR TITLE
Updated working Theia IDE installation

### PR DESCRIPTION
**Pull request by jpbarto**
**Issue #, if available:**

**Description of changes:**

The following change adds an LC script to install the Eclipse Theia IDE onto a SageMaker notebook instance.

**Testing Done**

- [x] Notebook Instance created successfully with the Lifecycle Configuration
- [x] Notebook Instance stopped and started successfully
- [x] Documentation in the script around any network access requirements
- [x] Documentation in the script around any IAM permission requirements
- [x] CLI commands used to validate functionality on the instance
- [x] New script link and description added to README.md

```
# Provide your commands here
/you/commands/here
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by vdabravolski** [comment]
Curious why this quite useful PR is not being merged for 2+ months?

**Comment by frannievas** [comment]
Hi, I tried running this example but I'm getting a `500 interval server error` while trying to open the theia editor. Any hints on what could be wrong?

**Comment by dmlause** [comment]
Hello, please resolve the merge conflicts and perform the testing steps again to confirm there are no additional updates needed for the latest runtime environment(s). Thanks.

**Comment by dmlause** [comment]
Closing this PR for inactivity

**Pull request closed without merging**
